### ISSUE TITLE
Incompatibility, some bugs and some suggestions :-)

### ISSUE THREAD

**Issue by MSAbaddon** [vtt-lair/token-replacer#30]
Hi,
first things first - this is a great module, I love it.

Due to this fact I want to use the module, but unfortunately ran into several issues:

- The module seems to be incompatible with the Assets Library of The Forge. I can select a folder within the Assets Library as a location for token images, but when I try to import actors an error is thrown

![image](https://user-images.githubusercontent.com/66370966/104821063-8a345e00-5839-11eb-8b9b-f473a420ea5f.png)

- When I manually create an actor in the actors tab with "replace token and portrait art" enabled, only the portrait art is replaced, the portrait stays at mystery man

![image](https://user-images.githubusercontent.com/66370966/104821122-fadb7a80-5839-11eb-93a2-b0edd1e8dff5.png)

- The randomization of tokens seems to not function corectly - out of three available images only two are used

![image](https://user-images.githubusercontent.com/66370966/104821176-5c9be480-583a-11eb-9bde-93e7476d0035.png)

- One feature suggestion: It would be great if token and portrait art could be handled separate from each other, e.g. by using a definable prefix like 'portrait' in the file names. That would allow a DM to put x files for the tokens and one different file for the portrait into the directory and let the module replace both in one step instead of having to manually choose the portrait every time.

![image](https://user-images.githubusercontent.com/66370966/104821362-81dd2280-583b-11eb-9d3f-d28f11b33f8e.png)

**Comment by vtt-lair** [comment]
Thanks for the feedback @MSAbaddon. I'm currently away on vacation, but I will look at this as soon as I'm back and able.

**Comment by MSAbaddon** [comment]
That's great news, thanks for the info and have a great vacation :-)

**Comment by MSAbaddon** [comment]
One more suggestion: When searching for tokens/portraits, include subfolders below the initial cr-folder. Would allow some more structure within folders which contain a lot of tokens (e.g. cr0 containing all the townsfolk, commoners, guards and desert guards tokens from Forgotten Adventures.

**Comment by vtt-lair** [comment]
@MSAbaddon Just to keep you updated, I've made a few fixes that I'm currently still testing. Should be released by this weekend:

- I've fixed the compatibility issue with The Asset Library of The Forge.
- I've fixed the issue with the portrait not updating on manually created actors. I'm still sitting with an issue where the first time the token is placed, the token isn't being updated. Will see if I can get this sorted out (is a known issue since the module was first released).
- I've changed the randomisation formula that seems to be working a bit better. Also remember that if you add any new images in the folder, you will have to refresh your foundry page to ensure the new image is cached.
- I've added the ability to specify a prefix for portraits in the settings. The prefix that you use must be exact, so if you use "portrait" then the file must be "portraitDeep_Scion.png", similarly if it's set to "p_" the file will have to be "p_Deep_Scion.png". _Portraits are only set once, usually on actor creation. I've added logic that if the portrait isn't set and there is a portrait for the actor, it will set it when you create a token but this will only happen once_.
- The last suggestion I started implementing, then realised it's a bit more involved. Because I cache the image names, they will be cached with those subfolders as part of the name. So when trying to see if the actor that you are using has an image, the format of my check will not have those subfolders as part of the check and then won't find the file(s). I'll spend some time to see if I can figure out a solution for this. _So I doubt this will be implemented by this weekend_

**Comment by MSAbaddon** [comment]
Wow, that's great news, thanks for the update :-)

**Comment by vtt-lair** [comment]
@MSAbaddon your requested enhancements and bug fixes has been released in v0.2.2

**Comment by MSAbaddon** [comment]
Awesome :-)

Did you also implement the subfolder suggestion?

One mor thing regarding portrait art: If I opt to replace both portrait and token and set a prefix, the module works fine as long as there actually is a portrait file available. If no portrait file is available though, no replacement happens (neither portrait nor token). Would be great if - in case no portrait is found - the module tries again to find a portrait ignoring the set prefix and instead use one of the available token images.

**Comment by vtt-lair** [comment]
I wasn't able to implement the subfolders.

Interesting, I did code it in such a way that it's supposed to fall back to the other if it wasn't found. Will see what's potting and create a hotfix for it.

**Comment by vtt-lair** [comment]
I did a hotfix release v 0.2.3 to fix the issue with the portrait art and fallback not working as expected. Should now be working.

**Comment by MSAbaddon** [comment]
Nice :-)
Just testet it and looks great.
One last thing I noticed - it sometimes happens that the first token being replaced looks like this:
![image](https://user-images.githubusercontent.com/66370966/106246296-2b45f000-620e-11eb-82eb-e0babab47af7.png)
