### ISSUE TITLE
Question: How does the token-replacer handle x/y CR?

### ISSUE THREAD

**Issue by Waldleufer** [vtt-lair/token-replacer#62]
My Folders are prenamed CR_1⁄4 ... but that doesn't seem to work quite. 

I wasn't able to find out what folder name to use instead, as `/` is not supported in folder names.

Thank you in advance!
Waldleufer

**Comment by Waldleufer** [comment]
comparing my setup 

![Screenshot 2021-04-02 184432](https://user-images.githubusercontent.com/22003632/113435632-83060080-93e3-11eb-81c8-b015675b9f56.png)

with your setup (shown by you in #59 )

![](https://user-images.githubusercontent.com/33215552/112798128-c0c5fa80-906c-11eb-9e30-73277412b60e.png)

I would assume that 
```
1/2 = 0_5
1/4 = 0_25
1/8 = 0_125
```

if I'm not mistaken? ;)

**Comment by Waldleufer** [comment]
So I went ahead and changed the 1/2 to 0_5 and so on and that solved the issue. Maybe you could put that information somewhere in the FAQ or README.md 😄 

Great Module! Thank you for your effort in putting it together 👍

**Comment by vtt-lair** [comment]
@Waldleufer, sorry for taking so long in getting back to you (time zones) and glad you were able to figure out the naming convention.

I'm assuming you are using FA's tokens... I'm actually not sure how the named their folders using "/", as in Windows that's not allowed for folder names. The reason I'm using 0_5, 0_25 and 0_125 (other than the Windows name conventions) is because that's the way the values are saved on the actor's data.

I'll add it to the README.md for better clarity, thanks for the suggestion.
