### ISSUE TITLE
Can't get Portrait Replacement to work.

### ISSUE THREAD

**Issue by kuzin** [vtt-lair/token-replacer#63]
I recorded a video of the issue: https://www.dropbox.com/s/vsm20ksxvk2dscl/Screen%20Recording%202021-05-02%20at%208.15.39%20PM.mov?dl=0

Note. I am not using the CR feature and this is in the Pathfinder 2 system.

Expected Behavior: 

I have two files, Augrael.png & p_Augrael.png
I drag the token out, Augrael.png is set to the Token Image & p_Augrael.png is set to the portrait.

Actual Behavior:

When 'Use NPC Difficulty Folder Structure' is checked:
I drag the token out, Augrael.png is set to the token image, the portrait is not set.

When 'Use NPC Difficulty Folder Structure' is unchecked:
I drag the token out, p_Augrael.png is set to the token image (the file meant for the portrait), the portrait is not set.

---

Also, when 'Use NPC Difficulty Folder Structure' is unchecked and attempting to change the settings, I get this console error: 

```
foundry.js:5253 TypeError: Cannot set property 'selected' of undefined
    at TokenReplacerSetup._updateObject (token-replacer.js:129)
    at TokenReplacerSetup._onSubmit (foundry.js:5251)
```

**Comment by kuzin** [comment]
I figured out the issue. There's a check to see if the portrait art is 'icons/svg/mystery-man.svg' but some other systems don't use this as default from the compendium (For Example PF2e).  

Maybe if there was a toggle to disable this check?

**Comment by vtt-lair** [comment]
@kuzin thanks for letting me know. I'll be giving this my attention in the next few days.

**Comment by vtt-lair** [comment]
@kuzin 'icons/svg/mystery-man.svg' is the default icon & portrait for an actor that Foundry uses when there is no portrait or token specified. It's not related the a specific game system.

The check I had in there was specifically add so that the portrait doesn't get updated every time that you drag an actor to the canvas, this was actually before I added the portrait prefix and was done so that the portrait doesn't change every time you drag the actor and you have different tokens for the same actor (different Goblin tokens for instance). 

However, since I've added the portrait prefix, I can actually remove this check as you can specify which image you want to use as the portrait.

I've also found the error thrown on the save. I'll be releasing these fixes in the next few hours.
