### ISSUE TITLE
Stopped working when using The Forge

### ISSUE THREAD

**Issue by domriozzi** [vtt-lair/token-replacer#78]
When using on The Forge, the Token Directory gives an error: 'Directory does not exist or is not accessible in this storage location.'

**Comment by vtt-lair** [comment]
Did you port over from your own hosting to The Forge? 

I know I fixed compatibility with The Assest Library on The Forge in January. Instead of [data], it be showing something like this:

![image](https://user-images.githubusercontent.com/33215552/132865745-8387e747-2dfe-4a40-b559-1c45256b9d95.png)

**Comment by vtt-lair** [comment]
I've just tested this again against my own Forge Asset Library and it's working. Since I'm not hosting directly with The Forge, I needed to install their The Forge module to access the asset library.

I might be wrong but I far as I know you can access image etc directly from user data when using Forge, meaning you'll have upload all the tokens you use to their asset library and access it from there.

**Comment by domriozzi** [comment]
Hey, thanks for the reply.

I didn't port, everything has always been on The Forge. The module used to
work perfectly.

I have all my tokens in a folder in my Forge Asset Library but it still
gives the error:
[image: Screenshot 2021-09-10 at 15.27.38.jpg]
[image: Screenshot 2021-09-10 at 15.27.05.jpg]

If I set it to Replace Token & Portrait Artwork, it replaces the
portrait but not the token:
[image: Screenshot 2021-09-10 at 15.31.17.jpg]

**Comment by vtt-lair** [comment]
That's super weird, did you update my module today (the last release was 15 days ago) or was it already updated and now it just stopped working?

Unfortunately you screenshots didn't work, so not seeing the actual error.

**Comment by domriozzi** [comment]
I just updated the screenshots, there should be links there now!

I just reinstalled it through the Forge Bazaar so it's up to date. I can't remember exactly when it stopped working but it was at least a few months ago.

**Comment by vtt-lair** [comment]
Uhmmmm, I'll have to investigate. Will create a trial account on The Forge and see if I can get to the bottom of this over the weekend. Will keep you updated and thanks for letting me know about this.

**Comment by domriozzi** [comment]
Thanks for getting back so quickly! Good luck!

**Comment by vtt-lair** [comment]
Hey @domriozzi. Sorry for taking so long in getting back to you. Been a busy couple of weeks.

I just tried a this on the Forge, using the same settings that you are using and was able to get both the token and portrait to change.

Would you possibly create a user for me on your world so I could maybe debug there and see what is happening?

**Comment by vtt-lair** [comment]
Closing this as it's been 4 months since last feedback
